<?php

namespace App\Helpers;

class ConuntryHelperEnhanced
{
   public static function getCountries(): array
    {
        return [
            "AF" => ["name" => "Afghanistan", "phone_code" => "+93"],
            "AL" => ["name" => "Albania", "phone_code" => "+355"],
            "DZ" => ["name" => "Algeria", "phone_code" => "+213"],
            "AD" => ["name" => "Andorra", "phone_code" => "+376"],
            "AO" => ["name" => "Angola", "phone_code" => "+244"],
            "AR" => ["name" => "Argentina", "phone_code" => "+54"],
            "AM" => ["name" => "Armenia", "phone_code" => "+374"],
            "AU" => ["name" => "Australia", "phone_code" => "+61"],
            "AT" => ["name" => "Austria", "phone_code" => "+43"],
            "AZ" => ["name" => "Azerbaijan", "phone_code" => "+994"],
            "BD" => ["name" => "Bangladesh", "phone_code" => "+880"],
            "BE" => ["name" => "Belgium", "phone_code" => "+32"],
            "BT" => ["name" => "Bhutan", "phone_code" => "+975"],
            "BR" => ["name" => "Brazil", "phone_code" => "+55"],
            "BG" => ["name" => "Bulgaria", "phone_code" => "+359"],
            "CA" => ["name" => "Canada", "phone_code" => "+1"],
            "CN" => ["name" => "China", "phone_code" => "+86"],
            "CO" => ["name" => "Colombia", "phone_code" => "+57"],
            "HR" => ["name" => "Croatia", "phone_code" => "+385"],
            "CZ" => ["name" => "Czech Republic", "phone_code" => "+420"],
            "DK" => ["name" => "Denmark", "phone_code" => "+45"],
            "EG" => ["name" => "Egypt", "phone_code" => "+20"],
            "FI" => ["name" => "Finland", "phone_code" => "+358"],
            "FR" => ["name" => "France", "phone_code" => "+33"],
            "DE" => ["name" => "Germany", "phone_code" => "+49"],
            "GR" => ["name" => "Greece", "phone_code" => "+30"],
            "HK" => ["name" => "Hong Kong", "phone_code" => "+852"],
            "HU" => ["name" => "Hungary", "phone_code" => "+36"],
            "IN" => ["name" => "India", "phone_code" => "+91"],
            "ID" => ["name" => "Indonesia", "phone_code" => "+62"],
            "IR" => ["name" => "Iran", "phone_code" => "+98"],
            "IQ" => ["name" => "Iraq", "phone_code" => "+964"],
            "IE" => ["name" => "Ireland", "phone_code" => "+353"],
            "IT" => ["name" => "Italy", "phone_code" => "+39"],
            "JP" => ["name" => "Japan", "phone_code" => "+81"],
            "JO" => ["name" => "Jordan", "phone_code" => "+962"],
            "KZ" => ["name" => "Kazakhstan", "phone_code" => "+7"],
            "KE" => ["name" => "Kenya", "phone_code" => "+254"],
            "KR" => ["name" => "Korea, South", "phone_code" => "+82"],
            "KW" => ["name" => "Kuwait", "phone_code" => "+965"],
            "LB" => ["name" => "Lebanon", "phone_code" => "+961"],
            "MY" => ["name" => "Malaysia", "phone_code" => "+60"],
            "MX" => ["name" => "Mexico", "phone_code" => "+52"],
            "NP" => ["name" => "Nepal", "phone_code" => "+977"],
            "NL" => ["name" => "Netherlands", "phone_code" => "+31"],
            "NZ" => ["name" => "New Zealand", "phone_code" => "+64"],
            "NG" => ["name" => "Nigeria", "phone_code" => "+234"],
            "NO" => ["name" => "Norway", "phone_code" => "+47"],
            "PK" => ["name" => "Pakistan", "phone_code" => "+92"],
            "PH" => ["name" => "Philippines", "phone_code" => "+63"],
            "PL" => ["name" => "Poland", "phone_code" => "+48"],
            "PT" => ["name" => "Portugal", "phone_code" => "+351"],
            "QA" => ["name" => "Qatar", "phone_code" => "+974"],
            "RO" => ["name" => "Romania", "phone_code" => "+40"],
            "RU" => ["name" => "Russia", "phone_code" => "+7"],
            "SA" => ["name" => "Saudi Arabia", "phone_code" => "+966"],
            "SG" => ["name" => "Singapore", "phone_code" => "+65"],
            "ZA" => ["name" => "South Africa", "phone_code" => "+27"],
            "ES" => ["name" => "Spain", "phone_code" => "+34"],
            "LK" => ["name" => "Sri Lanka", "phone_code" => "+94"],
            "SE" => ["name" => "Sweden", "phone_code" => "+46"],
            "CH" => ["name" => "Switzerland", "phone_code" => "+41"],
            "SY" => ["name" => "Syria", "phone_code" => "+963"],
            "TW" => ["name" => "Taiwan", "phone_code" => "+886"],
            "TH" => ["name" => "Thailand", "phone_code" => "+66"],
            "TR" => ["name" => "Turkey", "phone_code" => "+90"],
            "UA" => ["name" => "Ukraine", "phone_code" => "+380"],
            "AE" => ["name" => "United Arab Emirates", "phone_code" => "+971"],
            "GB" => ["name" => "United Kingdom", "phone_code" => "+44"],
            "US" => ["name" => "United States", "phone_code" => "+1"],
            "VN" => ["name" => "Vietnam", "phone_code" => "+84"],
            "YE" => ["name" => "Yemen", "phone_code" => "+967"],
        ];
    }
}
