<?php

namespace App\Helpers;

class CountryHelper
{
    public static function getCountries(): array
    {
        return [
            "AF" => "Afghanistan",
            "AL" => "Albania",
            "DZ" => "Algeria",
            "AD" => "Andorra",
            "AO" => "Angola",
            "AR" => "Argentina",
            "AM" => "Armenia",
            "AU" => "Australia",
            "AT" => "Austria",
            "AZ" => "Azerbaijan",
            "BD" => "Bangladesh",
            "BE" => "Belgium",
            "BT" => "Bhutan",
            "BR" => "Brazil",
            "BG" => "Bulgaria",
            "CA" => "Canada",
            "CN" => "China",
            "CO" => "Colombia",
            "HR" => "Croatia",
            "CZ" => "Czech Republic",
            "DK" => "Denmark",
            "EG" => "Egypt",
            "FI" => "Finland",
            "FR" => "France",
            "DE" => "Germany",
            "GR" => "Greece",
            "HK" => "Hong Kong",
            "HU" => "Hungary",
            "IN" => "India",
            "ID" => "Indonesia",
            "IR" => "Iran",
            "IQ" => "Iraq",
            "IE" => "Ireland",
            "IT" => "Italy",
            "JP" => "Japan",
            "JO" => "Jordan",
            "KZ" => "Kazakhstan",
            "KE" => "Kenya",
            "KR" => "Korea, South",
            "KW" => "Kuwait",
            "LB" => "Lebanon",
            "MY" => "Malaysia",
            "MX" => "Mexico",
            "NP" => "Nepal",
            "NL" => "Netherlands",
            "NZ" => "New Zealand",
            "NG" => "Nigeria",
            "NO" => "Norway",
            "PK" => "Pakistan",
            "PH" => "Philippines",
            "PL" => "Poland",
            "PT" => "Portugal",
            "QA" => "Qatar",
            "RO" => "Romania",
            "RU" => "Russia",
            "SA" => "Saudi Arabia",
            "SG" => "Singapore",
            "ZA" => "South Africa",
            "ES" => "Spain",
            "LK" => "Sri Lanka",
            "SE" => "Sweden",
            "CH" => "Switzerland",
            "SY" => "Syria",
            "TW" => "Taiwan",
            "TH" => "Thailand",
            "TR" => "Turkey",
            "UA" => "Ukraine",
            "AE" => "United Arab Emirates",
            "GB" => "United Kingdom",
            "US" => "United States",
            "VN" => "Vietnam",
            "YE" => "Yemen",
        ];
    }
}
